In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("C:\\01Data\\Urjit\\AIML\\Breast-Cancer-Detection-using-Machine-Learning-master\\cancer dataset.csv")

In [3]:
from sklearn.preprocessing import LabelEncoder
labelencoder_Y=LabelEncoder()
df.iloc[:,1]=labelencoder_Y.fit_transform(df.iloc[:,1].values)

In [4]:
x = df.drop('diagnosis',axis = 1).values
y = df['diagnosis'].values

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25,random_state = 0)

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [7]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(random_state = 0)

In [8]:
logreg.fit(x_train,y_train)
print("Logistic Regression Training Accuracy :",logreg.score(x_train,y_train))

Logistic Regression Training Accuracy : 0.9906103286384976


In [9]:
y_pred1 = logreg.predict(x_test)

In [10]:
from sklearn.metrics import confusion_matrix
cm1 = confusion_matrix(y_test,y_pred1)
cm1

array([[87,  3],
       [ 3, 50]], dtype=int64)

In [11]:
TP = cm1[0][0]
TN = cm1[1][1]
FP = cm1[0][1]
FN = cm1[1][0]
print("Logistic Regression Testing Accuracy :",(TP+TN)/(TP+TN+FP+FN))

Logistic Regression Testing Accuracy : 0.958041958041958


In [12]:
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier(criterion = 'entropy',random_state = 0)

In [13]:
dtree.fit(x_train,y_train)
print("Decision Tree Classifier Training Accuracy :",dtree.score(x_train,y_train))

Decision Tree Classifier Training Accuracy : 1.0


In [14]:
y_pred2 = dtree.predict(x_test)

In [15]:
cm2 = confusion_matrix(y_test,y_pred2)
cm2

array([[85,  5],
       [ 2, 51]], dtype=int64)

In [16]:
TP = cm2[0][0]
TN = cm2[1][1]
FP = cm2[0][1]
FN = cm2[1][0]
print("Decision Tree Classifier Testing Accuracy :",(TP+TN)/(TP+TN+FP+FN))

Decision Tree Classifier Testing Accuracy : 0.951048951048951


In [17]:
from sklearn.ensemble import RandomForestClassifier
rfor = RandomForestClassifier(random_state = 0)

In [18]:
rfor.fit(x_train,y_train)
print("Random Forest Classifier Training Accuracy :",rfor.score(x_train,y_train))

Random Forest Classifier Training Accuracy : 1.0


In [19]:
y_pred3 = rfor.predict(x_test)

In [20]:
cm3 = confusion_matrix(y_test,y_pred3)
cm3

array([[88,  2],
       [ 1, 52]], dtype=int64)

In [21]:
TP = cm3[0][0]
TN = cm3[1][1]
FP = cm3[0][1]
FN = cm3[1][0]
print("Random Forest Classifier Testing Accuracy :",(TP+TN)/(TP+TN+FP+FN))

Random Forest Classifier Testing Accuracy : 0.9790209790209791


The Random Forest Classifier had the highest accuracy among the 3 models. 

If there is a high non linearity and complex relationship between dependent and independent variables, a tree model will outperform a regression method. This being said, Random Forest makes use of multiple decision trees together. The idea behind Random Forest is that a large number of tress working together will outperform any individual tree. The reason for this is that the trees protect each other from their individual errors.